export const products = [
  {
    id: 1,
    name: 'Organic Tomatoes',
    category: 'vegetables',
    price: 60,
    unit: 'kg',
    rating: 4.8,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=500',
    farmer: 'Ramesh Kumar',
    location: 'Ahmedabad, Gujarat',
    organic: true,
    discount: 10,
    stock: 'In Stock',
    description: 'Fresh, juicy organic tomatoes grown without pesticides. Perfect for salads and cooking.'
  },
  {
    id: 2,
    name: 'Fresh Apples',
    category: 'fruits',
    price: 120,
    unit: 'kg',
    rating: 4.7,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?auto=format&fit=crop&q=80&w=500',
    farmer: 'Priya Singh',
    location: 'Himachal Pradesh',
    organic: false,
    discount: 0,
    stock: 'In Stock',
    description: 'Sweet and crunchy apples from the hills of Himachal Pradesh. Rich in flavor and nutrients.'
  },
  {
      id: 3,
      name: "Organic Brown Rice",
      category: "grains",
      price: 95,
      unit: "kg",
      rating: 4.9,
      reviews: 156,
      image:
        "https://plus.unsplash.com/premium_photo-1725878608892-628a5b22358e?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D?auto=format&fit=crop&q=80&w=500",
      farmer: "Suresh Patel",
      location: "Punjab",
      organic: true,
      discount: 5,
      stock: "In Stock",
      description:
        "Nutrient-rich organic brown rice. Grown using traditional farming methods for authentic taste.",
    },
    {
      id: 4,
      name: "Farm Fresh Milk",
      category: "dairy",
      price: 60,
      unit: "liter",
      rating: 4.6,
      reviews: 87,
      image:
        "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=500",
      farmer: "Amit Patel",
      location: "Maharashtra",
      organic: true,
      discount: 0,
      stock: "In Stock",
      description:
        "Pure and fresh cow milk from our farm. No preservatives or additives added.",
    },
    {
      id: 5,
      name: "Red Onions",
      category: "vegetables",
      price: 40,
      unit: "kg",
      rating: 4.5,
      reviews: 112,
      image:
        "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?auto=format&fit=crop&q=80&w=500",
      farmer: "Rajesh Verma",
      location: "Maharashtra",
      organic: false,
      discount: 15,
      stock: "In Stock",
      description:
        "Fresh red onions with a strong flavor. Essential for Indian cooking and salads.",
    },
    {
      id: 6,
      name: "Organic Turmeric Powder",
      category: "spices",
      price: 180,
      unit: "250g",
      rating: 4.9,
      reviews: 203,
      image:
        "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&q=80&w=500",
      farmer: "Lakshmi Devi",
      location: "Karnataka",
      organic: true,
      discount: 0,
      stock: "In Stock",
      description:
        "Pure organic turmeric powder with high curcumin content. Freshly ground for maximum flavor and health benefits.",
    },
    {
      id: 7,
      name: "Green Peas",
      category: "vegetables",
      price: 80,
      unit: "kg",
      rating: 4.6,
      reviews: 78,
      image:
        "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=500",
      farmer: "Sanjay Kumar",
      location: "Uttar Pradesh",
      organic: false,
      discount: 0,
      stock: "Limited Stock",
      description:
        "Fresh green peas, perfect for curries, pulao, and snacks. Harvested at peak ripeness.",
    },
    {
      id: 8,
      name: "Organic Honey",
      category: "organic",
      price: 350,
      unit: "500g",
      rating: 4.8,
      reviews: 167,
      image:
        "https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&q=80&w=500",
      farmer: "Harpreet Singh",
      location: "Punjab",
      organic: true,
      discount: 8,
      stock: "In Stock",
      description:
        "Pure, raw, and unprocessed honey from wildflower fields. Rich in antioxidants and natural enzymes.",
    },
    {
      id: 9,
      name: "Fresh Potatoes",
      category: "vegetables",
      price: 30,
      unit: "kg",
      rating: 4.5,
      reviews: 92,
      image:
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=500",
      farmer: "Ramesh Kumar",
      location: "Uttar Pradesh",
      organic: false,
      discount: 0,
      stock: "In Stock",
      description:
        "Fresh, firm potatoes perfect for curries, fries, and mashed potatoes. Grown in nutrient-rich soil.",
    },
    {
      id: 10,
      name: "Organic Wheat Flour",
      category: "grains",
      price: 65,
      unit: "kg",
      rating: 4.7,
      reviews: 145,
      image:
        "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&q=80&w=500",
      farmer: "Suresh Patel",
      location: "Punjab",
      organic: true,
      discount: 0,
      stock: "In Stock",
      description:
        "Stone-ground organic wheat flour. Perfect for making rotis, chapatis, and other traditional breads.",
    },
    {
      id: 11,
      name: "Fresh Oranges",
      category: "fruits",
      price: 90,
      unit: "kg",
      rating: 4.6,
      reviews: 87,
      image:
        "https://images.unsplash.com/photo-1459663296021-50769c04b149?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZnJlc2glMjBvcmFuZ2V8ZW58MHx8MHx8fDA%3D",
      farmer: "Priya Singh",
      location: "Maharashtra",
      organic: false,
      discount: 12,
      stock: "In Stock",
      description:
        "Juicy, sweet oranges rich in Vitamin C. Perfect for juicing or eating fresh.",
    },
    {
      id: 12,
      name: "Organic Ghee",
      category: "dairy",
      price: 550,
      unit: "500g",
      rating: 4.9,
      reviews: 178,
      image:
        "https://media.istockphoto.com/id/1341502956/photo/ghee-butter-in-glass-jar-top-view.webp?a=1&b=1&s=612x612&w=0&k=20&c=-FsoGfo2yVi6gbgHLRYpOLJZTrcJ5MoRqVIBXVPcAXw=",
      farmer: "Amit Patel",
      location: "Gujarat",
      organic: true,
      discount: 5,
      stock: "In Stock",
      description:
        "Pure, clarified butter made from organic cow milk. Rich in flavor and perfect for Indian cooking.",
    },
];

export const HomeProducts = [
    {
        id: 1,
        name: 'Organic Tomatoes',
        category: 'vegetables',
        price: 60,
        unit: 'kg',
        rating: 4.8,
        reviews: 124,
        image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=500',
        farmer: 'Ramesh Kumar',
        location: 'Ahmedabad, Gujarat',
        organic: true,
        discount: 10,
        stock: 'In Stock',
        description: 'Fresh, juicy organic tomatoes grown without pesticides. Perfect for salads and cooking.'
      },
      {
        id: 2,
        name: 'Fresh Apples',
        category: 'fruits',
        price: 120,
        unit: 'kg',
        rating: 4.7,
        reviews: 98,
        image: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?auto=format&fit=crop&q=80&w=500',
        farmer: 'Priya Singh',
        location: 'Himachal Pradesh',
        organic: false,
        discount: 0,
        stock: 'In Stock',
        description: 'Sweet and crunchy apples from the hills of Himachal Pradesh. Rich in flavor and nutrients.'
      },

    {
          id: 4,
          name: "Farm Fresh Milk",
          category: "dairy",
          price: 60,
          unit: "liter",
          rating: 4.6,
          reviews: 87,
          image:
            "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=500",
          farmer: "Amit Patel",
          location: "Maharashtra",
          organic: true,
          discount: 0,
          stock: "In Stock",
          description:
            "Pure and fresh cow milk from our farm. No preservatives or additives added.",
        },
        {
          id: 5,
          name: "Red Onions",
          category: "vegetables",
          price: 40,
          unit: "kg",
          rating: 4.5,
          reviews: 112,
          image:
            "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?auto=format&fit=crop&q=80&w=500",
          farmer: "Rajesh Verma",
          location: "Maharashtra",
          organic: false,
          discount: 15,
          stock: "In Stock",
          description:
            "Fresh red onions with a strong flavor. Essential for Indian cooking and salads.",
        },
];

export const HomeFarmer = [
  {
    id: 1,
    name: "Ramesh Kumar",
    image:
      "https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?auto=format&fit=crop&q=80&w=500",
    location: "Ahmedabad, Gujarat",
    rating: 4.8,
    reviews: 156,
    products: ["Organic Tomatoes", "Potatoes", "Onions"],
    organic: true,
    experience: "15+ years",
    verified: true,
    bio: "Third-generation farmer specializing in organic vegetables. Our farm has been certified organic for over 10 years.",
    activeOrders: 45,
    totalSales: "2.5L+",
  },
  {
    id: 2,
    name: "Priya Singh",
    image:
      "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?auto=format&fit=crop&q=80&w=500",
    location: "West Bengal",
    rating: 4.7,
    reviews: 189,
    products: ["Organic Rice", "Wheat", "Pulses"],
    organic: true,
    experience: "8+ years",
    verified: true,
    bio: "Passionate about sustainable farming. We use traditional methods combined with modern technology.",
    activeOrders: 32,
    totalSales: "1.8L+",
  },
  {
    id: 3,
    name: "Amit Patel",
    image:
      "https://plus.unsplash.com/premium_photo-1661811677567-6f14477aa1fa?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmFybXxlbnwwfHwwfHx8MA%3D%3D",
    location: "Maharashtra",
    rating: 4.9,
    reviews: 312,
    products: ["Farm Eggs", "Organic Vegetables", "Fruits"],
    organic: true,
    experience: "12+ years",
    verified: true,
    bio: "Family-run poultry farm focusing on free-range eggs and organic vegetables.",
    activeOrders: 38,
    totalSales: "2.1L+",
  },
];

export const cropsAndGrains = [
  {
    id: 1,
    name: "Organic Wheat",
    image:
      "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&q=80&w=500",
    price: 65,
    unit: "kg",
    farmer: "Suresh Patel",
    location: "Punjab",
    organic: true,
  },
  {
    id: 2,
    name: "Basmati Rice",
    image:
      "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=500",
    price: 90,
    unit: "kg",
    farmer: "Rajesh Verma",
    location: "Uttar Pradesh",
    organic: false,
  },
  {
    id: 3,
    name: "Organic Lentils",
    image:
      "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?auto=format&fit=crop&q=80&w=500",
    price: 120,
    unit: "kg",
    farmer: "Amit Patel",
    location: "Maharashtra",
    organic: true,
  },
];

export const dairyProducts = [
  {
    id: 1,
    name: "Organic Milk",
    price: 60,
    unit: "Liter",
    rating: 4.8,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&q=80&w=500",
    farmer: "Ravi Sharma",
    location: "Punjab",
  },
  {
    id: 2,
    name: "Desi Ghee",
    price: 550,
    unit: "500g",
    rating: 4.9,
    reviews: 178,
    image: "https://images.unsplash.com/photo-1631237764664-5c95d62c1f83?auto=format&fit=crop&q=80&w=500",
    farmer: "Amit Patel",
    location: "Gujarat",
  },
  {
    id: 3,
    name: "Paneer (Cottage Cheese)",
    price: 320,
    unit: "kg",
    rating: 4.7,
    reviews: 123,
    image: "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&q=80&w=500",
    farmer: "Suresh Kumar",
    location: "Rajasthan",
  },
  {
    id: 4,
    name: "Fresh Butter",
    price: 250,
    unit: "500g",
    rating: 4.6,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1592838065595-91fb8a7c143f?auto=format&fit=crop&q=80&w=500",
    farmer: "Priya Singh",
    location: "Maharashtra",
  },
];

export const organicProducts = [
  {
    id: 1,
    name: "Organic Honey",
    price: 350,
    unit: "500g",
    rating: 4.8,
    reviews: 167,
    image: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&q=80&w=500",
    farmer: "Harpreet Singh",
    location: "Punjab",
  },
  {
    id: 2,
    name: "Organic Wheat Flour",
    price: 65,
    unit: "kg",
    rating: 4.7,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&q=80&w=500",
    farmer: "Suresh Patel",
    location: "Punjab",
  },
  {
    id: 3,
    name: "Organic Ghee",
    price: 550,
    unit: "500g",
    rating: 4.9,
    reviews: 178,
    image: "https://images.unsplash.com/photo-1631237764664-5c95d62c1f83?auto=format&fit=crop&q=80&w=500",
    farmer: "Amit Patel",
    location: "Gujarat",
  },
  {
    id: 4,
    name: "Organic Turmeric Powder",
    price: 120,
    unit: "250g",
    rating: 4.8,
    reviews: 134,
    image: "https://images.unsplash.com/photo-1592838065595-91fb8a7c143f?auto=format&fit=crop&q=80&w=500",
    farmer: "Meera Sharma",
    location: "Karnataka",
  },
];

export const marketPrices = [
  { id: 1, name: "Wheat", category: "Grains", price: 2500, unit: "Quintal", location: "Punjab" },
  { id: 2, name: "Rice", category: "Grains", price: 3200, unit: "Quintal", location: "West Bengal" },
  { id: 3, name: "Maize", category: "Grains", price: 2100, unit: "Quintal", location: "Madhya Pradesh" },
  { id: 4, name: "Cotton", category: "Cash Crops", price: 6000, unit: "Quintal", location: "Maharashtra" },
  { id: 5, name: "Sugarcane", category: "Cash Crops", price: 300, unit: "Ton", location: "Uttar Pradesh" },
  { id: 6, name: "Potato", category: "Vegetables", price: 25, unit: "Kg", location: "Bihar" },
  { id: 7, name: "Tomato", category: "Vegetables", price: 40, unit: "Kg", location: "Karnataka" },
  { id: 8, name: "Onion", category: "Vegetables", price: 50, unit: "Kg", location: "Maharashtra" },
];

export const rentProducts = [
  {
    id: 1,
    name: "Tractor (John Deere 5050D)",
    category: "Machinery",
    price: 2000,
    unit: "per day",
    location: "Punjab",
    image: "https://images.unsplash.com/photo-1564868480822-32f714a0e763?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dHJhY3RvcnxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 2,
    name: "Rotavator",
    category: "Machinery",
    price: 1500,
    unit: "per day",
    location: "Haryana",
    image: "https://cdn.pixabay.com/photo/2015/08/05/20/40/tractor-877049_1280.jpg",
  },
  {
    id: 3,
    name: "Land for Lease (2 Acres)",
    category: "Land",
    price: 25000,
    unit: "per year",
    location: "Maharashtra",
    image: "https://cdn.pixabay.com/photo/2016/11/23/15/13/wheat-fields-1853434_1280.jpg",
  },
  {
    id: 4,
    name: "Water Pump Set",
    category: "Irrigation",
    price: 500,
    unit: "per day",
    location: "Gujarat",
    image: "https://cdn.pixabay.com/photo/2014/04/07/04/46/pump-318331_1280.jpg",
  },
];

export  const farmers = [
  {
    id: 1,
    name: "Ramesh Kumar",
    image:
      "https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?auto=format&fit=crop&q=80&w=500",
    location: "Ahmedabad, Gujarat",
    rating: 4.8,
    reviews: 156,
    products: ["Organic Tomatoes", "Potatoes", "Onions"],
    organic: true,
    experience: "15+ years",
    verified: true,
    bio: "Third-generation farmer specializing in organic vegetables. Our farm has been certified organic for over 10 years.",
    activeOrders: 45,
    totalSales: "2.5L+",
  },
  {
    id: 2,
    name: "Priya Singh",
    image:
      "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?auto=format&fit=crop&q=80&w=500",
    location: "West Bengal",
    rating: 4.7,
    reviews: 189,
    products: ["Organic Rice", "Wheat", "Pulses"],
    organic: true,
    experience: "8+ years",
    verified: true,
    bio: "Passionate about sustainable farming. We use traditional methods combined with modern technology.",
    activeOrders: 32,
    totalSales: "1.8L+",
  },
  {
    id: 3,
    name: "Suresh Patel",
    image:
      "https://images.unsplash.com/photo-1595034583162-8d716e054e82?auto=format&fit=crop&q=80&w=500",
    location: "Punjab",
    rating: 4.9,
    reviews: 234,
    products: ["Wheat", "Rice", "Corn"],
    organic: false,
    experience: "20+ years",
    verified: true,
    bio: "Leading wheat producer in Punjab. Our farm uses advanced irrigation systems for better yield.",
    activeOrders: 56,
    totalSales: "3.2L+",
  },
  {
    id: 4,
    name: "Amit Patel",
    image:
      "https://images.unsplash.com/photo-1592838065595-91fb8a7c143f?auto=format&fit=crop&q=80&w=500",
    location: "Maharashtra",
    rating: 4.9,
    reviews: 312,
    products: ["Farm Eggs", "Organic Vegetables", "Fruits"],
    organic: true,
    experience: "12+ years",
    verified: true,
    bio: "Family-run poultry farm focusing on free-range eggs and organic vegetables.",
    activeOrders: 38,
    totalSales: "2.1L+",
  },
  {
    id: 5,
    name: "Rajesh Verma",
    image:
      "https://images.unsplash.com/photo-1595034547796-2f96c880c65b?auto=format&fit=crop&q=80&w=500",
    location: "Uttar Pradesh",
    rating: 4.6,
    reviews: 145,
    products: ["Organic Potatoes", "Onions", "Garlic"],
    organic: true,
    experience: "10+ years",
    verified: true,
    bio: "Specializing in root vegetables. Our farm practices natural farming methods.",
    activeOrders: 28,
    totalSales: "1.5L+",
  },
  {
    id: 6,
    name: "Sanjay Kumar",
    image:
      "https://images.unsplash.com/photo-1595034580074-2da817e48bd1?auto=format&fit=crop&q=80&w=500",
    location: "Maharashtra",
    rating: 4.7,
    reviews: 178,
    products: ["Fresh Onions", "Tomatoes", "Chilies"],
    organic: false,
    experience: "18+ years",
    verified: true,
    bio: "Traditional farming methods with modern storage facilities for longer shelf life.",
    activeOrders: 42,
    totalSales: "2.8L+",
  },
];